### ISSUE TITLE
Script editing

### ISSUE THREAD

**Issue by niera87** [fr31b3u73r/miThermoHygro#1]
Hello, I am just starting journey with Domoticz and Python an I have some problem to edit miThermoHygro script.  How I need to change this part of script:

# sensor dictionary to add own sensors
# key is MAC of BT sensor, value is sensor ID
sensor_dict = {}
sensor_dict["4C:65:A8:D0:XX:XX"] = 1
sensor_dict["4C:65:A8:D0:XX:XX"] = 2

I know the mac address of the  sensor, and my dummy sensors in domoticz have idx 1 and 2. But I'm not sure how to put this information in the script.
What should I do when I don't use any specific username and passwor on domoticz?

**Comment by fr31b3u73r** [comment]
Hi niera87,

regarding configuration:
The idx value of your dummy sensors are the values behind "=", so for your setup just as in the source code you copied. In your case you only need to adjust the MAC addresses to match those of your sensors.

regarding using script withoud user/pass:
If you do not have any user and password for Domoticz you should be able to call API without authorization. In that case just edit send_to_domoticz and remove auth part - like this:
`requests.get(url)`

BR

**Comment by niera87** [comment]
Hi,

Thank you very much for the explanation. So I understand, that the
parenthesis in the "sensor_dict = {}" remains empty?

Best regards,
PN

2018-06-22 14:48 GMT+02:00 fr31b3u73r <notifications@github.com>:

**Comment by Creo2005** [comment]
Hi,
1. Error for this operator: dict.iteritems() - for python3 is: dict.items()
2. My idx from domotikz 
![2020-03-14 07 31 27 pm](https://user-images.githubusercontent.com/10849149/76687296-424a1680-662b-11ea-9464-5960cd82bee3.png)
- 36
I not have data for my domoticz :(
`#!/usr/bin/env python2
import binascii
import base64
import requests
from bluepy.btle import UUID, Peripheral, ADDR_TYPE_PUBLIC, DefaultDelegate

# domoticz configuration
DOMOTICZ_SERVER   = "127.0.0.1:8080"
DOMOTICZ_USERNAME = ""
DOMOTICZ_PASSWORD = ""

# sensor dictionary to add own sensors
# key is MAC of BT sensor, value is sensor ID
sensor_dict = {}
sensor_dict["4C:65:A8:DD:89:A3"] = 36

# constants for polling sensor; do not change!
BATTERY_HANDLE = 0x0018
TEMP_HUM_WRITE_HANDLE = 0x0010
TEMP_HUM_READ_HANDLE = 0x000E
TEMP_HUM_WRITE_VALUE = bytearray([0x01, 0x10])

battery_level = -1
sensor_id = -1

class TempHumDelegate(DefaultDelegate):
	def __init__(self):
		DefaultDelegate.__init__(self)

	def handleNotification(self, cHandle, data):
		if (cHandle == TEMP_HUM_READ_HANDLE):
			data = data.rstrip(' \t\r\n\0')
			temperature = data.split(" ")[0][2:]
			humidity = data.split(" ")[1][2:]
			comfort_type = get_comfort_type(humidity)
			if (sensor_id != -1 and battery_level > -1):
				request_url = 'http://' + DOMOTICZ_SERVER + '/json.htm?type=command&param=udevice&idx=' + str(sensor_id) + '&nvalue=0&svalue=' + temperature + ';' + humidity + ';' + comfort_type + '&battery=' + str(battery_level)
				send_to_domoticz(request_url)

def send_to_domoticz(url):
	requests.get(url)

def get_comfort_type(humidity):
	comfort_type = "0"
	if float(humidity) < 40:
		comfort_type = "2"
	elif float(humidity) <= 70:
		comfort_type = "1"
	elif float(humidity) > 70:
		comfort_type = "3"
	return comfort_type

def get_battery_value():
	battery_value = 0;
	try:
		battery_value = p.readCharacteristic(BATTERY_HANDLE)
	finally:
		return int(binascii.b2a_hex(battery_value), 16)

def handle_temp_hum_value():
	p.writeCharacteristic(TEMP_HUM_WRITE_HANDLE, TEMP_HUM_WRITE_VALUE)
	while True:
		if p.waitForNotifications(1.0):
			break

for key, value in sensor_dict.items():
	try:
		sensor_id = value
		p = Peripheral(key)
		p.withDelegate(TempHumDelegate())
		battery_level = get_battery_value()
		handle_temp_hum_value()
		p.disconnect()
	except:
		pass`
